
API_ID: 10464138
API_HASH: 4185aaae27c0ee23420255f2627ddb5f
BOT_TOKEN: 5752625093:AAEwnbeb1RM7EcgRxkrPmJxeWGnwdz1LIw4


MONGO_URL:  mongodb+srv://bikashhalder1234444:bikash890@cluster0.c7hlkrv.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-19708.c14.us-east-1-2.ec2.cloud.redislabs.com:19708
REDIS_PORT: 19708
REDIS_PASS: YJtJt3pPJFZk5FjcXxRisd0icVKI9KsL

SESSION_API_ID: 10464138
SESSION_API_HASH: 4185aaae27c0ee23420255f2627ddb5f
SESSION_STRING:  1BVtsOMUBu3jPxhIP5AgSGyYIQhX2_EgE1rAgI1x2uWApY0pnKRj76FDZycA9zmhovbbjw5KJOmIjJhvcuD5xJ1RpWSVMK2IbjLJ1eYYvnLHAm6shAPvjQVBc8d3Sh0St5xwm2cJgLwDyoM7o8mocxcPJ7GyeY__Io_i4QqiHhFNUZQCSjEdvVNzN6l01VNHybh3u2dXqN2BLbBn9e0ZMFqood69Fee0Ghg3krKQZYPJ78aEDD2vQkFe6C3AmvLz0mNv0xSKUZ_E8j7P0aUJS6q21NNtkYmkRIBJyGJme-HIGtRSq6osCyxHRMh_iEGkmAA_eL8eX2GttPj5dq6H-T3BB9ayPBnA=

ADMINS: 
  - 5195866238

OWNER: 5195866238

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"
